services:
  server:
    container_name: backend
    # image: node:18-bullseye
    build: ./
    command: npm start
    working_dir: /usr/src/server
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/server